=== Copa04/WebsiteJocuri/continut/resurse/persoane.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="persoane">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="persoana" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nume" type="xs:string"/>
                            <xs:element name="prenume" type="xs:string"/>
                            <xs:element name="varsta" type="xs:integer"/>
                            <xs:element name="DateCV">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="experienta_profesionala" type="xs:string"/>
                                        <xs:element name="Educatie" type="xs:string"/>
                                        <xs:element name="Limbi_straine" type="xs:string"/>
                                        <xs:element name="Competente_digitale" type="xs:string"/>
                                        <xs:element name="Info_suplimentare" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="adresa">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="strada" type="xs:string"/>
                                        <xs:element name="numar" type="xs:string"/>
                                        <xs:element name="localitate" type="xs:string"/>
                                        <xs:element name="judet" type="xs:string"/>
                                        <xs:element name="tara" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Copa04/WebsiteJocuri/continut/resurse/persoane.xml
<?xml version="1.0" encoding="UTF-8" ?>
<persoane 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="persoane.xsd">

    <persoana id="1">
        <nume>Popescu</nume>
        <prenume>Ion</prenume>
        <varsta>23</varsta>

    <DateCV>
        <experienta_profesionala>Marketing digital</experienta_profesionala>
        <Educatie>Licenta in marketing</Educatie>
        <Limbi_straine>Engleza Franceza</Limbi_straine>
        <Competente_digitale>Google ADS</Competente_digitale>
        <Info_suplimentare>Permis conducere</Info_suplimentare>
    </DateCV>
    <adresa>
        <strada>Strada Anastasie Panu</strada>
        <numar>29</numar>
        <localitate>Iasi</localitate>
        <judet>Iasi</judet>
        <tara>Romania</tara>
    </adresa>
    </persoana>
    
    <persoana id="2">
        <nume>Mircilescu</nume>
        <prenume>Cosmin</prenume>
        <varsta>21</varsta>

    <DateCV>
        <experienta_profesionala>Software Engineer</experienta_profesionala>
        <Educatie>Licenta in Tehnologia Informatiei</Educatie>
        <Limbi_straine>Engleza</Limbi_straine>
        <Competente_digitale>Google ADS</Competente_digitale>
        <Info_suplimentare>Permis conducere</Info_suplimentare>
    </DateCV>
    <adresa>
        <strada>Strada Teascului</strada>
        <numar>22</numar>
        <localitate>Iasi</localitate>
        <judet>Iasi</judet>
        <tara>Romania</tara>
    </adresa>
    </persoana>
</persoane>
